apiVersion: v1
kind: Service
metadata:
  name: servertask
  labels:
    app: servertask
spec:
  selector:
    app: servertask
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: LoadBalancer